### ISSUE TITLE
OpenMP test suite crash

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#107]
The following tests crash with OpenMP (need to change parallelization const to 1)

This part of int matmul fallback

```Nim
  test "Integer Matrix-Matrix Multiplication fallback":
    ## TODO: test with slices
    let a = [[1,2,3],
             [4,5,6]].toTensor()

    let b = [[7,  8],
             [9, 10],
             [11,12]].toTensor()

    let ab = [[ 58, 64],
              [139,154]].toTensor()

    check: a * b == ab
```

Furthermore, there is a delayed "attempt to read from nil" that seem to be trigger and happens some tests later. Maybe due to GC collecting the data?

==> Todo: As OpenMP is deactivated for small matrices (<1000 elements), it's probably better to just test that the common operations work on 40x40 matrices in test_openmp as the small size might be the trigger.

==> Todo: a stress-test with large matrices that triggers OpenMP

**Comment by mratsim** [comment]
A dedicated test suite has been added by https://github.com/mratsim/Arraymancer/commit/d860cee7a2ef624e68f0bb5010a7257ff0a7db0f.

Note: OpenMP must be compiled with stacktraces off otherwise OpenMP segfaults in a popFrame.

The new test suite generates:
- a segfault + core dump
- Unhandled exception: Attempt to read from nil
- Index out of bounds
- rarely, a stack trace in `gescal` with Attempt to read from nil

From GDB:
```
[New LWP 23159]
[New LWP 23164]
[New LWP 23162]
[New LWP 23163]
[New LWP 23161]
[New LWP 23160]
[New LWP 23157]
[New LWP 23158]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./bin/test_load_openmp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f75f44d91cc in _IO_flush_all_lockp () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f75ea297700 (LWP 23159))]
(gdb) bt
#0  0x00007f75f44d91cc in _IO_flush_all_lockp () from /usr/lib/libc.so.6
#1  0x00007f75f44d9336 in _IO_cleanup () from /usr/lib/libc.so.6
#2  0x00007f75f449442b in __run_exit_handlers () from /usr/lib/libc.so.6
#3  0x00007f75f44944da in exit () from /usr/lib/libc.so.6
#4  0x00005617b622d1e7 in signalHandler ()
#5  <signal handler called>
#6  0x00005617b62766bc in gescal_w7FGITPB9bUpM0qE1E4R7UQ ()
#7  0x00005617b627ade0 in gemm_macro_kernel_vwv9a8KfguRP4qtSQqvdYaQ._omp_fn.0 ()
#8  0x00007f75f4a488ee in gomp_thread_start (xdata=<optimized out>) at /build/gcc/src/gcc/libgomp/team.c:120
#9  0x00007f75f481b08a in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f75f45531bf in clone () from /usr/lib/libc.so.6
```
gescal code
```C
N_NIMCALL(void, gescal_w7FGITPB9bUpM0qE1E4R7UQ)(NI m, NI n, NI alpha, tySequence_qwqHTkRvwhrRyENtudHQ7g** X, NI offX, NI incRowX, NI incColX) {
	{
		if (!!((alpha == ((NI) 0)))) goto LA3_;
		{
			NI j;
			NI i;
			j = (NI)0;
			i = ((NI) 0);
			{
				while (1) {
					NI TM_19bM2QWZhUjwRF8bIi3cQjA_24;
					if (!(i < n)) goto LA7;
					j = i;
					{
						NI i_2;
						NI i_3;
						i_2 = (NI)0;
						i_3 = ((NI) 0);
						{
							while (1) {
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_19;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_20;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_21;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_22;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_23;
								if (!(i_3 < m)) goto LA10;
								i_2 = i_3;
								TM_19bM2QWZhUjwRF8bIi3cQjA_19 = mulInt(i_2, incRowX);
								TM_19bM2QWZhUjwRF8bIi3cQjA_20 = mulInt(j, incColX);
								TM_19bM2QWZhUjwRF8bIi3cQjA_21 = addInt((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_19), (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_20));
								TM_19bM2QWZhUjwRF8bIi3cQjA_22 = addInt((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_21), offX);
								if ((NU)((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_22)) >= (NU)((*X)->Sup.len)) raiseIndexError();
								stareq__tk9bwZBdb9bO9baUcUN2AX89bQmetadataArray((&(*X)->data[(NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_22)]), alpha);
								TM_19bM2QWZhUjwRF8bIi3cQjA_23 = addInt(i_3, ((NI) 1));
								i_3 = (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_23);
							} LA10: ;
						}
					}
					TM_19bM2QWZhUjwRF8bIi3cQjA_24 = addInt(i, ((NI) 1));
					i = (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_24);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI j_2;
			NI i_4;
			j_2 = (NI)0;
			i_4 = ((NI) 0);
			{
				while (1) {
					NI TM_19bM2QWZhUjwRF8bIi3cQjA_30;
					if (!(i_4 < n)) goto LA14;
					j_2 = i_4;
					{
						NI i_5;
						NI i_6;
						i_5 = (NI)0;
						i_6 = ((NI) 0);
						{
							while (1) {
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_25;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_26;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_27;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_28;
								NI TM_19bM2QWZhUjwRF8bIi3cQjA_29;
								if (!(i_6 < m)) goto LA17;
								i_5 = i_6;
								TM_19bM2QWZhUjwRF8bIi3cQjA_25 = mulInt(i_5, incRowX);
								TM_19bM2QWZhUjwRF8bIi3cQjA_26 = mulInt(j_2, incColX);
								TM_19bM2QWZhUjwRF8bIi3cQjA_27 = addInt((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_25), (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_26));
								TM_19bM2QWZhUjwRF8bIi3cQjA_28 = addInt((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_27), offX);
								if ((NU)((NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_28)) >= (NU)((*X)->Sup.len)) raiseIndexError();
								(*X)->data[(NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_28)] = ((NI) 0);
								TM_19bM2QWZhUjwRF8bIi3cQjA_29 = addInt(i_6, ((NI) 1));
								i_6 = (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_29);
							} LA17: ;
						}
					}
					TM_19bM2QWZhUjwRF8bIi3cQjA_30 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_19bM2QWZhUjwRF8bIi3cQjA_30);
				} LA14: ;
			}
		}
	}
	LA1_: ;
}
```

**Comment by mratsim** [comment]
closed by https://github.com/mratsim/Arraymancer/commit/daa068c615c7fe16d7a549f21e0030771b64c6ce
